"""Presenters the CMS does not know, filled in by hand.

The CMS carries a presenter for most of the archive, but not for the lecture
programmes: 49 of the lectures Varya reviewed have no presenter and no guest
in our data at all, so the speaker axis, the heaviest signal in the ranker,
was blind for every one of them. She filled them in by hand on 2026-09-16
(«Заполнить ведущих», 86cbhq9q8).

This lives in its own file rather than being written back into
`library_tags.jsonl`, for the same reason the editor's YouTube verdicts do:
the tag file is regenerated by the tagging batch, and hand work that a
machine run can destroy is hand work that will be lost. Keyed on
``content_id``, which is what the sheet carries and what survives a re-ingest
of the same episode under a new hash.
"""

from __future__ import annotations

import csv
from pathlib import Path


def load_presenters(path: Path) -> dict[str, list[str]]:
    """content_id -> the presenters named for it, in the order given.

    A missing file means "nobody has filled any in", which callers must treat
    as the old behaviour rather than as an error: the table is maintained by
    hand and can lag a fresh checkout, exactly like the programme table.
    """
    if not path.exists():
        return {}
    out: dict[str, list[str]] = {}
    # utf-8-sig and stripped header names, for the same reasons as the
    # programme table: a Sheets export carries a byte-order mark, and a stray
    # space in a header makes the column unreachable and empties the table.
    with open(path, encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames:
            reader.fieldnames = [(name or "").strip() for name in reader.fieldnames]
        for row in reader:
            content_id = (row.get("content_id") or "").strip()
            names = split_presenters(row.get("presenter") or "")
            if content_id and names:
                out[content_id] = names
    return out


def split_presenters(raw: str) -> list[str]:
    """Split a cell that may name several people.

    «Лев Гудков, Анна Качкаева, Наталья Тихонова, Эмиль Паин» is one panel and
    four speakers; keeping it as one string would make the ranker look for a
    person of that name and find nobody.
    """
    return [part.strip() for part in str(raw).split(",") if part.strip()]
