{{- if and .Values.streamlit.enabled .Values.streamlit.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rainrag.fullname" . }}-streamlit-secret
  labels:
    {{- include "rainrag.streamlit.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-token: {{ .Values.streamlit.authToken | quote }}
{{- end }}
